language: java
jdk: oraclejdk8
sudo: required

matrix:
  include:
    - dist: trusty
      env: dist="14.04 LTS trusty"
    - dist: xenial
      env: dist="16.04 LTS xenial"

before_install:
- sudo apt-get -qq update

install:
- sudo apt-get -qq install git
- bash build-onos.sh

script:
- sudo bash install-onos.sh
- sudo bash test-onos.sh

notifications:
  email:
      on_success: never
      # More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
