language: java
sudo: required
dist: xenial

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get -y install git mininet

script:
- bash build-onos.sh
- sudo bash install-onos.sh
- sudo bash test-onos.sh

notifications:
  email:
      on_success: never
      # More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
