language: java
sudo: required

matrix:
  include:
    - dist: trusty
    - dist: xenial

before_install:
- sudo apt-get -qq update

install:
- sudo apt-get -qq install git
- bash build-onos.sh

script:
- sudo bash install-onos.sh
- sudo bash test-onos.sh

notifications:
  email:
      on_success: never
      # More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
